<a href="https://colab.research.google.com/github/dsvalencias/MachineLearning/blob/main/Assignment_1_Linear_Algebra_and_Probability.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Assignment 1: Linear Algebra and Probability**

In [ ]:
import numpy as np

In [ ]:
TD = np.array([[2, 3, 0, 3, 7],
              [0, 5, 5, 0, 3],
              [5, 0, 7, 3, 3],
              [3, 1, 0, 9, 9],
              [0, 0, 7, 1, 3],
              [6, 9, 4, 6, 0]])
L = np.array([5, 2, 3, 6, 4, 3])

In [ ]:
print("TD")
print(TD)
print("L")
print(L)

TD
[[2 3 0 3 7]
 [0 5 5 0 3]
 [5 0 7 3 3]
 [3 1 0 9 9]
 [0 0 7 1 3]
 [6 9 4 6 0]]
L
[5 2 3 6 4 3]


First, TD matrix is representing the amount of ocurrencies of a word in every document. So, we have to normalize it respecting the probability proportional to the frequency of t_i in d_j
In other words.

${P(D,T)} = {P(T|D)} * {P(D)}$

In [ ]:
def partA(TD):
  #Getting D probabilites
  T_shape, D_shape = np.shape(TD)
  D_probability = np.ones(D_shape) * 1 / D_shape
  #Get occurrencies of every word in each document ( column )
  T_sum_D = np.sum(TD, axis=0)
  T_probability_in_D = np.divide(TD, T_sum_D)
  #Divide each word ocurrence in each document ( position ) by all occurencies in a doc
  T_D_prob = np.multiply(T_probability_in_D, D_probability)
  return T_D_prob

In [ ]:
T_D_prob = partA(TD)
print("P(T,D)=\n%s" % T_D_prob)
#The sum of probabilities of choosing a word in a document must be 1.0
print("Sum of P(T,D)= %s" % np.sum(T_D_prob))

P(T,D)=
[[0.025      0.03333333 0.         0.02727273 0.056     ]
 [0.         0.05555556 0.04347826 0.         0.024     ]
 [0.0625     0.         0.06086957 0.02727273 0.024     ]
 [0.0375     0.01111111 0.         0.08181818 0.072     ]
 [0.         0.         0.06086957 0.00909091 0.024     ]
 [0.075      0.1        0.03478261 0.05454545 0.        ]]
Sum of P(T,D)= 1.0


Now, we must use the Bayes theorem in order to find P(T|D)

${P(T|D)} = {P(D,T)} / {P(D)}$

Since we got P(D,T) in Part A and P(D) is an array of 0.2 (it will be shown in Part D) since docs has an uniform distribution

In [ ]:
def partB(TD):
  #Part B
  T_shape, D_shape = np.shape(TD)
  D_probability = np.ones(D_shape) * 1 / D_shape
  T_given_D_prob = np.divide(T_D_prob, D_probability)
  return T_given_D_prob

In [ ]:
T_given_D_prob = partB(TD)
print("P(T|D)= %s" % T_given_D_prob)

P(T|D)= [[0.125      0.16666667 0.         0.13636364 0.28      ]
 [0.         0.27777778 0.2173913  0.         0.12      ]
 [0.3125     0.         0.30434783 0.13636364 0.12      ]
 [0.1875     0.05555556 0.         0.40909091 0.36      ]
 [0.         0.         0.30434783 0.04545455 0.12      ]
 [0.375      0.5        0.17391304 0.27272727 0.        ]]


In [ ]:
T_given_D_prob.sum(axis=0)

array([1., 1., 1., 1., 1.])

In a similar fashion we can obtain P(D|T) and the process of getting P(T) will be shown in part E

${P(D|T)} = {P(D,T)} / {P(T)}$

In [ ]:
def partC(TD):
  T_count = np.sum(TD)
  t_sum = np.sum(TD, axis=1)
  #Divide by the total count of words
  T_probability = np.divide(t_sum, T_count)
  print(T_D_prob)
  print(T_probability)
  D_given_T_prob = np.divide(T_D_prob.transpose(), T_probability)
  return D_given_T_prob

In [ ]:
D_given_T_prob = partC(TD)
print("P(D|T))= %s" % D_given_T_prob.transpose())

[[0.025      0.03333333 0.         0.02727273 0.056     ]
 [0.         0.05555556 0.04347826 0.         0.024     ]
 [0.0625     0.         0.06086957 0.02727273 0.024     ]
 [0.0375     0.01111111 0.         0.08181818 0.072     ]
 [0.         0.         0.06086957 0.00909091 0.024     ]
 [0.075      0.1        0.03478261 0.05454545 0.        ]]
[0.14423077 0.125      0.17307692 0.21153846 0.10576923 0.24038462]
P(D|T))= [[0.17333333 0.23111111 0.         0.18909091 0.38826667]
 [0.         0.44444444 0.34782609 0.         0.192     ]
 [0.36111111 0.         0.35169082 0.15757576 0.13866667]
 [0.17727273 0.05252525 0.         0.38677686 0.34036364]
 [0.         0.         0.57549407 0.08595041 0.22690909]
 [0.312      0.416      0.14469565 0.22690909 0.        ]]


Since TD has a m x n shape and both T and D are vectors then:
*   T must have a mx1 shape; m = 6
*   D must have a 1xn shape; n = 5

Now, D has an uniform probability function therefore, D must have 1/n probability or 1/5



In [ ]:
def partD(TD):
  T_shape, D_shape = np.shape(TD)
  #print(D_shape)
  D_probability = np.ones(D_shape) * 1 / D_shape
  return D_probability

In [ ]:
D_probability = partD(TD)
print("P(D)= %s" % D_probability)
print("Sum of P(D)= %s" % np.sum(D_probability))

P(D)= [0.2 0.2 0.2 0.2 0.2]
Sum of P(D)= 1.0


In this part, P(T) depends on the posibility of every word and it can be infered using the amount of occurrencies row of TD

In [ ]:
def partE(TD):
  T_count = np.sum(TD)
  #Get total amount of word occurrencies 
  t_sum = np.sum(TD, axis=1)
  #Divide by the total count of words
  T_probability = np.divide(t_sum, T_count)
  return T_probability

In [ ]:
T_probability = partE(TD)
print("P(T)= %s" % T_probability)
print("Sum of P(T)= %s" % np.sum(T_probability))

P(T)= [0.14423077 0.125      0.17307692 0.21153846 0.10576923 0.24038462]
Sum of P(T)= 1.0


In this part, E[l] is the expected value of the random variable l corresponding to the length of a randomly chosen term. l in this case is a discrete variable cause words can't have float characters. So in this case we use this formula

$\mu = \operatorname{E}[X] = \sum_{i=1}^n p_i x_i$






In [ ]:
def partF(TD):
  #Multiply lengths of words with their probability itself
  L_Expected_Vector = np.multiply(L, T_probability)
  #Realize the summation
  L_Expected_Value = np.sum(L_Expected_Vector)
  return L_Expected_Value

In [ ]:
L_Expected_Value = partF(TD)
print("E[L]= %s" % L_Expected_Value)
print(np.average(L))

E[L]= 3.9038461538461533
3.8333333333333335


In this part, Var(l) is the variance of the random variable l. Is the expectation of the squared deviation of a random variable from its mean.

$\operatorname{Var}(X) = \sum_{i=1}^n p_i\cdot(x_i - \mu)^2$

In [ ]:
def partG(TD):
  #Substract lenghts with expected value of l
  var_aux = L - L_Expected_Value
  #Power them by 2
  var_aux = np.power(var_aux,2)
  #Multiply them with their probability itself
  L_Variance_Vector = np.multiply(var_aux, T_probability)
  L_Variance_Value = np.sum(L_Variance_Vector)
  return L_Variance_Value

In [ ]:
print("L con numpy")
print(np.var(L,ddof=1))

L con numpy
2.166666666666667


In [ ]:
L_Variance_Value = partG(TD)
print("Var(L)= %s" % L_Variance_Value)

Var(L)= 1.8946005917159765
