<a href="https://colab.research.google.com/github/dsvalencias/MachineLearning/blob/main/Assignment_2_Bayesian_Decision_Theory_and_Parametric_Estimation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Import dataset from github routine

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

url = 'https://raw.githubusercontent.com/dsvalencias/MachineLearning/main/Datasets/diabetes.csv'
data = pd.read_csv(url)
print(data.columns.values)
data.shape

['Pregnancies' 'Glucose' 'BloodPressure' 'SkinThickness' 'Insulin' 'BMI'
 'DiabetesPedigreeFunction' 'Age' 'Outcome']


(768, 9)

In [2]:
#Separating features from class label(outcome)
X_features = data.loc[:, "Pregnancies":"Age"].to_numpy()
print("X: %s %s" % (type(X_features), X_features.shape))
Y_label = data.loc[:, "Outcome"].to_numpy()
print("Y:  %s %s" % (type(Y_label), Y_label.shape))

X: <class 'numpy.ndarray'> (768, 8)
Y:  <class 'numpy.ndarray'> (768,)


In [3]:
#Separating all dataset into training and validation subsets

from sklearn.gaussian_process import GaussianProcessClassifier
from sklearn.gaussian_process.kernels import RBF
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_features, Y_label, test_size=0.33, random_state=42)

In [13]:
#import a GaussianProcessClassifier using all features -> and it should be one by one like .fit(X_train[0], y_train) .fit(X_train[1], y_train) ...
kernel = 1.0 * RBF(1.0)
gpc = GaussianProcessClassifier(kernel=kernel,random_state=0).fit(X_train, y_train)
y_predict = gpc.predict(X_test)
gpc.score(X_train, y_train)
#gpc.predict_proba(X_test)

0.791828793774319

In [14]:
#Get accuracy, precision and recall values
from sklearn import metrics
accuracy = metrics.accuracy_score(y_test, y_predict)
precision = metrics.precision_score(y_test, y_predict)
recall = metrics.recall_score(y_test, y_predict)
print("Accuracy: %f, Precision: %f, Recall: %f" % (accuracy, precision, recall))

Accuracy: 0.740157, Precision: 0.628205, Recall: 0.569767


In [15]:
#Draw curve for posterior distribution -> Use matplotlib for that
metrics.roc_curve(y_test, y_predict)

(array([0.        , 0.17261905, 1.        ]),
 array([0.        , 0.56976744, 1.        ]),
 array([2, 1, 0]))